### ISSUE TITLE
Wait support?

### ISSUE THREAD

**Issue by stephanbuys** [youngking/consul-rust#2]
Hi, awesome client, does it support the wait functionality to detect changes immediately? https://www.consul.io/docs/agent/http.html

**Comment by stephanbuys** [comment]
@youngking, just wanted to check if the project is active?

**Comment by youngking** [comment]
Sorry, I didn't use rust for these days, my interest now turned to the swift. I just declared deprecated this project in the readme, thanks for your pointing out.
